### ISSUE TITLE
ESMM根本跑不通

### ISSUE THREAD

**Issue by thormacy** [qiaoguan/deep-ctr-prediction#1]
第一个错误就是esmm.py line46中user_id上一行少了一个逗号。。
想问下这个代码跑过么

**Comment by qiaoguan** [comment]
跑过一部分， 你说的这个可能当时写的时候没注意吧，还有就是代码在自己使用的基础上有一些删减， 但是基本逻辑是没有问题的。  可以参考下，根据自己的需求做一些修改

**Comment by thormacy** [comment]
有跑通的代码可以参考么？

**Comment by qiaoguan** [comment]
不知道你有没有阅读过代码，这个代码都是跑不通的，因为数据默写是用的hadoop上的数据，我只是给了个参考， 因为要你自己的数据，你可以去找一个开源的数据集，然后把数据转换成你自己定义的tfrecord格式，然后你需要用到的feature在input_fn里面定义。

**Comment by thormacy** [comment]
ok. 谢谢，我去看看
