### ISSUE TITLE
内存溢出

### ISSUE THREAD

**Issue by meilejw** [qiaoguan/deep-ctr-prediction#10]
程序一直卡在这个地方，然后占用的内存暴涨，最后退出，请问博主有遇到过类似问题吗？
![20191227163021](https://user-images.githubusercontent.com/8514516/71509440-3c635580-28c6-11ea-83de-0421b10ea610.jpg)

**Comment by qiaoguan** [comment]
把input_fn里面的prefetch 里面的参数调小试试

**Comment by meilejw** [comment]
内存问题解决了 但是最后预估出来的cvr都是0 会是正样本太少造成的吗？

**Comment by qiaoguan** [comment]
检查下你的代码逻辑，一般结果可能会很小，很接近0，但一般不会是0

**Comment by meilejw** [comment]
试了下loss加权求和，cvr不再是0了，应该是cvr的梯度太大把cvr带跑了，但是最终效果不太好
想试下不做loss求和，设置不同的学习率分别优化，用Estimator优化两个loss该怎么实现呢？

**Comment by qiaoguan** [comment]
没太懂你的意思，完全两个loss没任何关系，不就是两个独立的项目？

**Comment by meilejw** [comment]
就是ctr和cvr用同一个网络，参数完全共享

**Comment by qiaoguan** [comment]
如果是完全一起训练，不管怎么做，不管ctr loss和cvr loss怎么定义，最终的loss只有一个
