### ISSUE TITLE
din dataset

### ISSUE THREAD

**Issue by ljcmheart** [qiaoguan/deep-ctr-prediction#11]
请问DIN模型中的训练数据可以提供下嘛

**Comment by qiaoguan** [comment]
我这儿没有可以提供给你的公开数据集， 你可以看下din原始paper的公开数据集，或者其他推荐相关的公开数据集

**Comment by ljcmheart** [comment]
那您能解释下代码中用到的数据集是什么意思嘛，主要是：product_id_att，creative_id_att，user_click_products_att，user_click_products_att

**Comment by ljcmheart** [comment]
因为官方的代码里没有用过多的特征，感觉您的代码比较有实用性，烦请帮忙解答一下含义和数据格式

**Comment by ljcmheart** [comment]
您好，您能帮忙解释下DIN代码中用到的数据集是什么意思嘛，主要是：product_id_att，creative_id_att，user_click_products_att，user_click_products_att，因为官方的代码里没有用过多的特征，感觉您的代码比较有实用性，烦请帮忙解答一下含义和数据格式，谢谢~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 晚上6:05
收件人:&nbsp;"qiaoguan/deep-ctr-prediction"<deep-ctr-prediction@noreply.github.com&gt;;
抄送:&nbsp;"♡♛♥"<1825330825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qiaoguan/deep-ctr-prediction] din dataset (#11)





 
我这儿没有可以提供给你的公开数据集， 你可以看下din原始paper的公开数据集，或者其他推荐相关的公开数据集
