### ISSUE TITLE
DIN样本数据含义

### ISSUE THREAD

**Issue by ljcmheart** [qiaoguan/deep-ctr-prediction#13]
您好，您能帮忙解释下DIN代码中用到的数据集是什么意思嘛，主要是：product_id_att，creative_id_att，user_click_products_att，user_click_products_att，因为官方的代码里没有用过多的特征，感觉您的代码比较有实用性，烦请帮忙解答一下含义和数据格式，谢谢~

**Comment by qiaoguan** [comment]
creative_id_att 表示该样本当前的creative_id， last_click_creativeid， 用户历史点击的creative_id序列，  其实我就是提供的一个参考代码，特征这些也是给的一个简单的参考方式，具体可以参考模型的实现部分(din.py 里面的attention_layer实现和输入)

**Comment by ljcmheart** [comment]
好的，明白了，刚接触attention机制，还是掌握的不够清楚，谢谢您啦~


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 晚上6:23
收件人:&nbsp;"qiaoguan/deep-ctr-prediction"<deep-ctr-prediction@noreply.github.com&gt;;
抄送:&nbsp;"♡♛♥"<1825330825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qiaoguan/deep-ctr-prediction] DIN样本数据含义 (#13)





 
creative_id_att 表示该样本当前的creative_id， last_click_creativeid， 用户历史点击的creative_id序列，  其实我就是提供的一个参考代码，特征这些也是给的一个简单的参考方式，具体可以参考模型的实现部分(din.py 里面的attention_layer实现和输入)

**Comment by ljcmheart** [comment]
大神，可以指点一下我DIN样本的具体格式嘛，attention部分的数据理不清楚，我现在是用户当前的商品id，和历史点击的id list，我做样本的时候是把历史点击id序列作为字符串存储了，在模型输入的时候历史点击的序列怎么处理呢，您可以截取一条您的数据给我看一下不，谢谢~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gq"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月11日(星期一) 晚上6:23
收件人:&nbsp;"qiaoguan/deep-ctr-prediction"<deep-ctr-prediction@noreply.github.com&gt;;
抄送:&nbsp;"♡♛♥"<1825330825@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [qiaoguan/deep-ctr-prediction] DIN样本数据含义 (#13)





 
creative_id_att 表示该样本当前的creative_id， last_click_creativeid， 用户历史点击的creative_id序列，  其实我就是提供的一个参考代码，特征这些也是给的一个简单的参考方式，具体可以参考模型的实现部分(din.py 里面的attention_layer实现和输入)

**Comment by qiaoguan** [comment]
你如果是用的tfrecord可以直接参考我的这个代码，历史点击的id list 在tfrecord格式对应的格式也是一个list，数据解析直接参考这份代码就OK，  如果不用tfrecord格式， 可以参考下 readme 里面的wide&deep里面的代码
