### ISSUE TITLE
attention unit

### ISSUE THREAD

**Issue by Cumberbatch08** [qiaoguan/deep-ctr-prediction#16]
您好，请教一个问题，计算attention unit的时候有一个max_seq_len，这里是对输入数据进行了padding吗？因为行为流有长有短

**Comment by qiaoguan** [comment]
超过长度的作截断，长度不够的padding补全

**Comment by Cumberbatch08** [comment]
这个操作是在预处理数据的时候吧，在代码里面没看到细节呢？

**Comment by qiaoguan** [comment]
对，训练数据就这样处理好， 代码里面有对padding部分的处理

**Comment by Cumberbatch08** [comment]
> 对，训练数据就这样处理好， 代码里面有对padding部分的处理

这部分代码可以贴一个链接吗？如果不做padding，到了attention dense那里会有问题，对吧？

**Comment by qiaoguan** [comment]
https://github.com/qiaoguan/deep-ctr-prediction/blob/master/Din/din.py#L67

**Comment by Cumberbatch08** [comment]
> https://github.com/qiaoguan/deep-ctr-prediction/blob/master/Din/din.py#L67

找到了，感谢感谢；一般就是根据行为流长度统计一下，然后做截取吧。
