### ISSUE TITLE
有没有 数据 放点demo上来  跑一下

### ISSUE THREAD

**Issue by adangadang** [qiaoguan/deep-ctr-prediction#2]

**Comment by qiaoguan** [comment]
你可以参考下Google开源的wide&deep，我readme里面有提供链接，那里面有一个小的数据库，你用我的代码跑的话， 你要先把数据转成tfrecord格式， 当然你也可以稍微改一点代码(input_fn里面)，用TextLineDataset格式也可以。

**Comment by yunchenran** [comment]
> 你可以参考下Google开源的wide&deep，我readme里面有提供链接，那里面有一个小的数据库，你用我的代码跑的话， 你要先把数据转成tfrecord格式， 当然你也可以稍微改一点代码(input_fn里面)，用TextLineDataset格式也可以。

链接里的wide_deep代码点开已经提示404了怎么破~

**Comment by qiaoguan** [comment]
我更新了README

**Comment by adangadang** [comment]
感谢分享  谢谢 加油
