### ISSUE TITLE
预测代码无法运行

### ISSUE THREAD

**Issue by 378994621** [qiaoguan/deep-ctr-prediction#8]
user_id = features['user_id']
  click_label = features['label']
  conversion_label = features['is_conversion']

  if mode == tf.estimator.ModeKeys.PREDICT:
    predictions = {
      'ctr_preds': ctr_preds,
      'cvr_preds': cvr_preds,
      'ctcvr_preds': ctcvr_preds,
      'user_id': user_id,
      'click_label': click_label,
      'conversion_label': conversion_label
    }
以上代码为ESSM第37-50行，从代码逻辑来看click_label，conversion_label是预测的对象，应该对应网络中的tensor啊，为什么从features直接读取啊？我的理解这两个label应该是分别从ctr_preds，ctcvr_preds转换过来的吧

**Comment by qiaoguan** [comment]
label是训练时候用的，  ctr_preds, ctcvr_preds 这个是模型训练好之后预测用的
